### ISSUE TITLE
Base.Printf.function() deprecated in Julia 1.4

### ISSUE THREAD

**Issue by Antmist** [JuliaMath/DecFP.jl#109]
Base.Printf needs to be changed to Printf.Printf with the dependency of Printf added to the top. 

I am not sure how this change effects other versions of Julia and it looks like the Compat.jl package has been solving this problem up to 1.3. 

I do a lot of work with the OmniSci.jl package and had to make this change to keep using the package, so at least this problem has a documented fix for anyone who is facing similar problems.

**Comment by stevengj** [comment]
Fortunately, `Printf` has been a standard library since Julia 1.0, so compatibility is not a problem if we make this change.

**Comment by stevengj** [comment]
Actually, this was already fixed a long time ago in #99, so I'm guessing you are using an old version of DecFP.  Make sure your Project.toml lists `DecFP = "0.4"` in the `[compat]` section.
