### ISSUE TITLE
Implement widen()

### ISSUE THREAD

**Issue by jmkuhn** [JuliaMath/DecFP.jl#113]
```
julia> widen(Float32)
Float64

julia> widen(Inf32)
Inf

julia> widen(Dec32)
ERROR: MethodError: no method matching widen(::Type{Dec32})
Closest candidates are:
  widen(::Type{T}) where T at operators.jl:808
  widen(::T) where T at operators.jl:807
  widen(::Type{Int8}) at int.jl:673
  ...
Stacktrace:
 [1] widen(::Type{Dec32}) at ./operators.jl:808
 [2] top-level scope at REPL[4]:1
```

**Comment by jmkuhn** [comment]
Should `widen(Dec128)` return `Dec128`?  I'm assuming we want `x == widen(x)` for any value `x`.  If we `widen` to `BigFloat` that relation wouldn't necessarily hold (ignoring the fact that we haven't implemented comparison with BigFloat).

**Comment by stevengj** [comment]
Seems like `widen(Dec128)` should throw a `MethodError` for now.
