### ISSUE TITLE
update Project.toml to allow SpecialFunctions v0.11

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/DecFP.jl#119]

**Comment by jmkuhn** [comment]
In master, SpecialFunctions v0.10 is supported in Project.toml.  There are a few issues that I would like to fix in the next few days then we will tag a release.

It doesn't appear that SpecialFunctions v0.11 has been released yet.

**Comment by JeffreySarnoff** [comment]
v0.11 is the version for SpecialFunctions#master (not released, yet available for use).  There are some situations (combinations of added packages) which force SpecialFunctions to downgrade from v0.10 to v0.9.  After the downgrade, one can add SpecialFunctions#master and regain v0.10 (and then some).  This happened with my setup.  There is no harm in adding v0.11 to the [compat] entry before it is released, your call.

**Comment by jmkuhn** [comment]
v0.11 is allowed in the current DecFP#master.
