### ISSUE TITLE
Rounding when parsing strings

### ISSUE THREAD

**Issue by jmkuhn** [JuliaMath/DecFP.jl#134]
```
julia> Dec32(10000000, RoundUp)
1.0e7

julia> Dec32("10000000", RoundUp)
1.000001e7

julia> Dec32("1.000000", RoundUp)
1.0

julia> Dec32("1.0000000", RoundUp)
1.000001
```
This appears to be an issue if the number of digits in the input string is greater than or equal to the number of digits in `maxintfloat(DecXX)` even when the input number is exactly representable.

**Comment by stevengj** [comment]
So, a bug in the underlying library? 😠 

Can we work around it just by stripping off trailing zeros and then adding them to the exponent?

**Comment by jmkuhn** [comment]
Yes, it appears to be a bug in the underlying library.  I'll look for the best way to fix.

**Comment by jmkuhn** [comment]
Intel has confirmed this bug.

> Indeed, this is an issue we need to fix. I will try to get back to you as soon as I can with a complete characterization of the problem (will check other similar functions as well), and we will provide you with a fix, before we will post an updated version of the library.

**Comment by jmkuhn** [comment]
Intel has provided a patch for this issue and they will release a new version of the library within a few weeks.

**Comment by stevengj** [comment]
No new release yet?  Unless by "weeks" they meant "years".

Can we apply the patch ourselves in Yggdrasil?
