### ISSUE TITLE
tag 1.0?

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/DecFP.jl#136]
Pre-1.0 versions are painful for packages to declare compatibility with, since every minor version bump is assumed to be breaking.

Are there any breaking changes planned on the horizon that I'm forgetting about, or should we go ahead and tag 1.0?

cc @jmkuhn, @quinnj

**Comment by jmkuhn** [comment]
I do plan to change `sigexp()` and export it, but since it isn't currently exported or documented I wouldn't consider this a breaking change.

Ideally I would like to have ARM working before tagging 1.0 but I can't promise this quickly.  I don't have any objection to tagging 1.0.

**Comment by stevengj** [comment]
Since both of those changes are non-breaking, they can be made in 1.x, so they don't need to hold up a 1.0 release.

**Comment by jmkuhn** [comment]
I'll add `sigexp`, `randn`, and `randexp` so we won't have to immediately tag 1.1 for these new features.  Everything else I have planned is a bug fix.

**Comment by stevengj** [comment]
I tagged 1.0 (https://github.com/JuliaRegistries/General/pull/16483) now that we have `sigexp`, since this changed the API (albeit the old one was internal).  Tagging 1.1 for `randn` etcetera is not a problem.
