### ISSUE TITLE
hash(T(Inf)) broken with current Julia master

### ISSUE THREAD

**Issue by jmkuhn** [JuliaMath/DecFP.jl#141]
```
julia> versioninfo()
Julia Version 1.6.0-DEV.1066
Commit b89c4a3cb5 (2020-09-28 08:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)

julia> hash(d32"Inf")
0x0000000000000001

julia> hash(Inf)
0x807bb202c9cbfc6f
```

**Comment by stevengj** [comment]
Is this a bug in DecFP, or in Julia?  It works in 1.5.

**Comment by jmkuhn** [comment]
I think this is due to a change in Julia.  I run the DecFP tests vs Julia master about once per week.  Due to issue https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/913 is has been a couple weeks since I ran the tests, but this is the first time I've seen this failure.  I haven't had time yet to investigate what has changed.

**Comment by jmkuhn** [comment]
Heisenbug - when run in the VSCode debugger, `hash(d32"Inf") == 0x807bb202c9cbfc6f`.

**Comment by jmkuhn** [comment]
`git bisect` indicates the first bad commit is https://github.com/JuliaLang/julia/commit/9adcdd42a03ae74ab8dcffd8f81b0880f909174b.

**Comment by jmkuhn** [comment]
This is a Julia/LLVM bug.  I have isolated a case that doesn't use DecFP.  I'll write and submit a Julia issue in the morning.

**Comment by stevengj** [comment]
Thanks for tracking this down.

**Comment by jmkuhn** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/38031
