### ISSUE TITLE
SpecialFunctions.logabsgamma return type changed

### ISSUE THREAD

**Issue by jmkuhn** [JuliaMath/DecFP.jl#145]
In SpecialFunctions v0.8 - v1.5 the return type of `logabsgamma` was `(Floatxx, Int32)`.  Starting with v1.6 it is `(Floatxx, Int)`.  Should we change the return type here and set the lower version limit on SpecialFunctions to v1.6?

**Comment by stevengj** [comment]
We might as well change the return type to `Int`, but I don't see why we would need to change the version limit?

(Technically, nothing requires us to use the same integer type as `logabsgamma(::Float64)` AFAICT.)

**Comment by jmkuhn** [comment]
You are correct; our input and return floating point types are different, so there is no reason our return integer type has to be the same.  The PR changes the return integer type but keeps the SpecialFunction version limits the same.
