### ISSUE TITLE
Use Requires.jl for SpecialFunctions?

### ISSUE THREAD

**Issue by fingolfin** [JuliaMath/DecFP.jl#162]
Right now, this package pulls in a lot of indirect dependencies just because it uses `SpecialFunctions`:
```
  [d360d2e6] + ChainRulesCore v1.15.0
  [9e997f8a] + ChangesOfVariables v0.1.3
  [55939f99] + DecFP v1.3.1
  [3587e190] + InverseFunctions v0.1.7
  [92d709cd] + IrrationalConstants v0.1.1
  [2ab3a3ac] + LogExpFunctions v0.3.15
  [276daf66] + SpecialFunctions v2.1.6
  [47200ebd] + DecFP_jll v2.0.3+1
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [05823500] + OpenLibm_jll v0.8.1+0
```
But as far as I know, the only reason to depend on `SpecialFunctions` is to install methods for `SpecialFunctions.logabsgamma` and `SpecialFunctions.gamma`.

This sounds like a perfect application for [Requires](https://github.com/JuliaPackaging/Requires.jl). Would you be willing to consider using that? Thank you!

**Comment by fingolfin** [comment]
OK, I think I misunderstood what Requires does: it seems it only avoids *loading* `SpecialFunctions` when it is not necessary; but `SpecialFunctions` still must be in `Project.toml`. So the indirect dependencies remain. (Those are annoying because I am `using Polymake` which then pulls in `Mongoc` which pulls in `DecFP`... and then the everything listed above.

**Comment by stevengj** [comment]
Yes, I don't think Requires.jl helps here.
