### ISSUE TITLE
the way DecFP decomposes converted floats is unpredictable

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaMath/DecFP.jl#163]
Can anyone explain the following?
```julia
◖◗ Dec64(1.25) |> sigexp
(1, 125, -2)

◖◗ Dec64(1.23) |> sigexp
(1, 1230000000000000, -15)
```
This looks suspiciously like a bug.

Choosing very negative exponents when unnecessary is not desirable behavior in certain contexts, see for example [here](https://gitlab.com/ExpandingMan/Parquet2.jl/-/issues/24).

**Comment by stevengj** [comment]
Nothing wrong here.  It's purely an artifact of the fact that `1.23` is not exactly representable, so you are really doing `DecFP(1.229999999999999982236431605997495353221893310546875)`.

If you start from a string it is more consistent:
```jl
julia> d"1.25" |> sigexp
(1, 125, -2)

julia> d"1.23" |> sigexp
(1, 123, -2)
```

**Comment by stevengj** [comment]
If you can't handle "big exponents", then you'll also have a problem with e.g.
```jl
julia> d"1.230000000000001" |> sigexp
(1, 1230000000000001, -15)
```
which seems more like a problem on your end.

**Comment by ExpandingMan** [comment]
Sorry, I obviously don't understand how the format actually works.

Guess this is another nail in the coffin that I need to be using integer-based decimals.

**Comment by stevengj** [comment]
Can you articulate a reason why an exponent of `-15` is a problem?   The value `d"1.23"` is still represented exactly.

The data "mangling" that you linked above (turning `0.8275` into `-1.820053504e9`) sounds like an unrelated bug in Parquet to me.

**Comment by stevengj** [comment]
In particular, note that according to the IEEE 754 standard, a single number may be stored with multiple equivalent representations involving different exponents, as  123×10⁻²=1230×10⁻³=12300×10⁻⁴, etcetera:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2913679/210286947-d2c38725-2c92-4705-9d25-c21ec8ee497e.png">

So the behavior of DecFP (via the Intel decimal fp library) in producing different representations of `1.23` depending on how it was constructed is conformant with the spec.

**Comment by ExpandingMan** [comment]
It's not a problem, there's nothing wrong with it, I just have a really wonky use case.

The parquet format doesn't allow distinct representations for individual decimal objects, it stores the exponent as a global metadata.  That means I have to pick something appropriate for all values and adjust each of them, so I'm concerned that I'll have to check if the exponent grows too large for some of the values.  I suppose it's not completely crazy to expect data stored in a parquet column to have similar exponents, but in my opinion that's an overly stringent requirement (particularly when most numerical libraries are more flexible than this) and I'll have to work around how they did it.

**Comment by stevengj** [comment]
Yes, what you are describing is a fixed-point format, or more precisely a [block floating-point](https://en.wikipedia.org/wiki/Block_floating_point) format.

**Comment by stevengj** [comment]
e.g. if you have a vector `x` of decimal floating-point data, you could convert to fixed-point with a common exponent via:
```jl
common_exponent = maximum(exponent10, x) - precision(eltype(x), base=10)
significands = round.(Int64, ldexp10.(x, -common_exponent))
```
which takes `x = [Dec64(1.24), Dec64(1.23), d"9.9999999999999", d"4.56789e-14"]` and yields `common_exponent = 16` and `significands = [12400000000000000, 12300000000000000, 99999999999999000, 457]`.

**Comment by ExpandingMan** [comment]
Ah... yes!  This is what I should be doing thanks.

What was bothering me was that if for example I want to encode $10^18$ and $10^{-5}$ I will run out of `Int64` to represent one or the other number and I was a bit torn on what the proper behavior was, I was planning on catching it and throwing an error.  But now I see that rounding off to zero is probably the correct way of handling it.

Thanks for your help!

**Comment by stevengj** [comment]
You could always call `convert` instead of `round` above if you want to throw an error.
