### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fingolfin** [JuliaMath/DecFP.jl#172]
It would be really nice there was a new DecFP release with my invalidation fixes in it. Pretty please, @stevengj ?

Hopefully with the fixed TagBot CI it will also again make tags / releases at https://github.com/JuliaMath/DecFP.jl/releases resp https://github.com/JuliaMath/DecFP.jl/tags

**Comment by stevengj** [comment]
Should be closed by https://github.com/JuliaRegistries/General/pull/86792

**Comment by fingolfin** [comment]
Thank you!
