### ISSUE TITLE
release tags not being created?

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/DecFP.jl#173]
For some reason, no releases are being tagged by @JuliaRegistrator, since version 1.1.  @fingolfin last updated TagBot in #165.

**Comment by quinnj** [comment]
I've had to redo the `DocumenterTools.genkeys()` process for several of my repos; I think there may have been a bunch of keys reset at some point automatically by GitHub.

**Comment by fingolfin** [comment]
Yes, the SSH_KEY needs to be setup. Please follow the instructions at <https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys>.

**Comment by fingolfin** [comment]
After you have done that you can hopefully generate the missing tags by going to <https://github.com/JuliaMath/DecFP.jl/actions/workflows/TagBot.yml> and then (if you have sufficient admin rights) select the "Run workflow" popup button; in there, set the "lookback" value high enough that it cover the missing commits -- it is given in days, the default is 3, but the 1.2 release was 2021-11-23, so I guess you need something like ... 800 or so, to be on the safe side *cough*. Disclaimer: I am not sure how well that works, and if it will detect all "missing" releases in one go, or if you have to maybe run this multiple times...

**Comment by stevengj** [comment]
Should be fixed now, thanks!

**Comment by stevengj** [comment]
But it doesn't look like it worked to create the 1.2 and 1.3 release tags retroactively :sad:

**Comment by fingolfin** [comment]
The run produced a "GitHub returned a 5xx error code". Maybe that day range is just to big. The last release was in July (?) so maybe try with something like 210 days instead?

**Comment by fingolfin** [comment]
... or just make another release ;-)

**Comment by stevengj** [comment]
I tried 210 days, no dice.

It's not a huge deal, we can just wait until the next release.
