### ISSUE TITLE
exact comparisons with binary values/directed conversions

### ISSUE THREAD

**Issue by simonbyrne** [JuliaMath/DecFP.jl#79]
Currently
```julia
julia> using DecFP

julia> d64"1e100" == 1e100
true
```
which might seem reasonable, except that
```julia
julia> big(1e100)
1.000000000000000015902891109759918046836080856394528138978132755774783877217038e+100
```

Since the library doesn't appear to offer comparisons, the one option would be to do it via directed conversions, e.g.
```julia
<(x::Float64, y::Dec64) = x < Float64(y, RoundUp)
<=(x::Float64, y::Dec64) = x <= Float64(y, RoundDown)
==(x::Float64, y::Dec64) = x == Float64(y, RoundUp) == Float64(y, RoundDown)
```

Is it possible to do this without touching the global rounding mode?

**Comment by ScottPJones** [comment]
Those comparisons won't be exact though.  Although it might be slower, if you want accurate results you might do better making a grisu like conversion of the binary floating point value, and then do the comparison using those values.  That technique would work for any binary floating point numbers, including `BigFloat` and the ones from `DoubleFloat.jl`, `Quadmath.jl`.  Since they would be exact comparisions, no rounding would be needed.

**Comment by simonbyrne** [comment]
why wouldn't they be exact?

**Comment by simonbyrne** [comment]
e.g.
```
x = d64"1e100"
using DecFP
setrounding(Dec64, RoundDown)
x < 1e100
```
return true

**Comment by ScottPJones** [comment]
If you have to do rounding, how can they be exact?

**Comment by simonbyrne** [comment]
Because we can control the direction of rounding. It is similar to the way that we compare floats to `Irrational`s (https://simonbyrne.github.io/talks/juliacon2018#/11), though requires a few extra checks since they can be equal.

**Comment by jmkuhn** [comment]
For the comparison
```
d64"1e100" == 1e100
```
the `Float64` `1e100` is getting promoted to a `Dec64`.  The comparison is really
```
d64"1e100" == convert(Dec64, 1e100)
```
Note
```
julia> convert(Dec64, 1e100)
1.0e100
```
That is exactly 1e100, not just approximately 1e100 rounded for printing.  From the `BigFloat` example above we know that `Float64(1e100)` is not exact, so what is happening?  `convert` (using `binary64_to_bid64`) is being clever.  It assumes for any `Float64` value `x`, we are representing a number in the range `x ± eps(x)/2`.  So for 1e100 we want a number in the range
```
julia> x = 1e100
1.0e100

julia> BigFloat(x) - BigFloat(eps(x))/2
9.999999999999999187694464984734645008629855152185828068577908031678078146264176e+99

julia> BigFloat(x) + BigFloat(eps(x))/2
1.000000000000000113036335721046371592809176197570473471098474708381759939807659e+100
```
`binary64_to_bid64` finds the number in this range that requires the fewest significant decimal digits to represent.

**Comment by jmkuhn** [comment]
```
julia> convert(Dec64, 1e100)
1.0e100

julia> convert(Dec128, 1e100)
1.000000000000000015902891109759918e100

julia> d64"1e100" == 1e100
true

julia> d128"1e100" == 1e100
false
```
