### ISSUE TITLE
string macro naming

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/DecFP.jl#86]
@ScottPJones noticed DecFP and DoubleFloats both export 'd64'. I was unaware of DecFP's use.  I wiil post a more general-purpose suggestion on discourse dev after sleeping on it to help others avoid this going forward.  I'll change my naming then.

**Comment by JeffreySarnoff** [comment]
And warn on use of the current name for a while.

**Comment by stevengj** [comment]
I don't see a big problem.  Name conflicts between disparate modules are ultimately avoidable only by requiring people to do `import`.   Trying to coordinate names doesn't scale.
