### ISSUE TITLE
InexactError for parsing/conversion

### ISSUE THREAD

**Issue by chbian** [JuliaMath/DecFP.jl#93]
I am running Julia 0.7.0 on Linus/CentOS and get the following InexactError,
```julia
julia> parse(Dec64, "3935767060.093896713")
ERROR: InexactError: parse(Dec64, 3935767060.093896713)
Stacktrace:
 [1] parse(::Type{Dec64}, ::String) at /home/user/.julia/packages/DecFP/3jJW7/src/DecFP.jl:66
 [2] top-level scope at none:0

julia> parse(Float64, "3935767060.093896713")
3.935767060093897e9

```
Parsing the value to `Float64` works fine. But it fails to parse to `Dec64`. Any idea why it happens? Thanks!

**Comment by chbian** [comment]
I guess I know the reason. IEEE 754 decimal 64 type may have 16 significant bits or decimal digits. The string I tried to parse in the previous example is too long for `Dec64`.

**Comment by stevengj** [comment]
I'm going to re-open this, since it's not clear that we should be throwing an `InexactError` here, and also for conversion between decimal types:
```
julia> Dec64(d128"3935767060.093896713")
ERROR: InexactError: convert(Dec64, 3.935767060093896713e9)
```
We should probably emulate the `Float64` behavior here and silently round when parsing/converting.
